<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function pagger($page, $size){
        $query = $this->createQueryBuilder('p')->getQuery();
        $paginator = new Paginator($query);

        $paginator->getQuery()
            ->setFirstResult($size * ($page - 1)) // Offset
            ->setMaxResults($size); // Limit

        return $paginator;
    }

    public function countAll(){
        return $this->createQueryBuilder('p')->select('count(p.id)')->getQuery()->getSingleScalarResult();
    }
}
